# DataSource Config
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-plus?serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 50
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.entity
logging:
  level:
    com:
      dao: debug

#默认请求参数
test: lin
markdown:
  path: F:\hexo\vuepress\docs
  bak-path: F:\hexo\vuepress\docs\.vuepress\picBak

#  path: F:\GitBook\Markdown入门到放弃
#  bak-path: F:\GitBook\Markdown入门到放弃\bak

  #  path: F:\GitBook\Linux
  #  bak-path: F:\GitBook\Linux\picBak

  #  path: F:\GitBook\Java学习
  #  bak-path: F:\GitBook\Java学习\picBak

  #  path: F:\GitBook\mysql
  #  bak-path:  F:\GitBook\mysql\picBak

  #  path: F:\GitBook\Spring
  #  bak-path:  F:\GitBook\Spring\picBak

  #  path: F:\GitBook\Spring-boot
  #  bak-path:  F:\GitBook\Spring-boot\picBak


  #  path:  F:\GitBook\复习题
  #  bak-path:  F:\GitBook\复习题\picBak

#  path: F:\GitBook\设计模式
#  bak-path:  F:\GitBook\设计模式\picBak

