language: node_js
node_js:
- 12.16.1

# 缓存目录，加速编译
cache:
  directories:
#  - node_modules

# 初始化环境
install:
  - npm install
#  - npm install -g vuepress
#  - npm install -D @vuepress/plugin-pwa@next
#  - npm install -D @vuepress/plugin-back-to-top@next
before_script: chmod a+x deploy.sh
script:
- bash ./deploy.sh

#deploy:
#  provider: pages
#  skip-cleanup: true
#  local_dir: docs/.vuepress/dist
#  github-token: "${access_token}"
#  keep-history: true
#  on:
#    branch: gh-pages
