language: node_js
node_js:
  - lts/*
script:
  - chmod u+x deploy.sh
  - ./deploy.sh
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB-TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: gh-pages