name: 博客发布

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - run: npm install
      - run: npm run docs:build
      - run: echo 'linqin.site' > ./docs/.vuepress/dist/CNAME

      - name: Build project
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.access_token}}
          publish_dir: ./docs/.vuepress/dist
      
      # - run: npm run docs:build
      # - run: cd docs/.vuepress/dist
      # - run: ls -a
      # - run: git init
      # - run: git add -A
      # - run: git commit -m 'action deploy'
      # - run: git push -f https://${{secrets.access_token}}@github.com/linqin07/vuepress-blog.git master:gh-pages 


     



